language: cpp
python:
  - "2.7_with_system_site_packages"
virtualenv:
  system_site_packages: true
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DEBIAN_FRONTEND=noninteractive;
      export APT_LISTCHANGES_FRONTEND=none;
      echo force-confold | sudo tee -a /etc/dpkg/dpkg.cfg;
      curl -k https://swift.im/keys/packages.key | sudo apt-key add -;
      echo 'deb http://us.archive.ubuntu.com/ubuntu xenial           main restricted universe multiverse' | sudo tee    /etc/apt/sources.list.d/xenial.list > /dev/null;
      echo 'deb http://us.archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list.d/xenial.list > /dev/null;
      echo 'deb http://us.archive.ubuntu.com/ubuntu xenial-security  main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list.d/xenial.list > /dev/null;
      echo 'deb http://us.archive.ubuntu.com/ubuntu xenial-updates   main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list.d/xenial.list > /dev/null;
      echo "deb http://packages.spectrum.im/spectrum2/ xenial main" | sudo tee -a /etc/apt/sources.list;
      echo "deb http://swift.im/packages/ubuntu/xenial beta main" | sudo tee -a /etc/apt/sources.list;
      echo "deb http://packages.prosody.im/debian $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list;
      sudo apt-get update -qq;
      sudo apt-get purge chromium-browser;
      sudo apt-get install -y --force-yes build-essential prosody ngircd python-sleekxmpp libswiften-dev libprotobuf-dev protobuf-compiler libpurple-dev libglib2.0-dev libdbus-glib-1-dev liblog4cxx10-dev libpopt-dev libboost-dev libboost-signals-dev libboost-system-dev libboost-thread-dev libboost-locale-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-date-time-dev libcppunit-dev libcommuni-dev libminiupnpc-dev libnatpmp-dev;
      sudo killall lua5.1;
    else
      brew update;
      brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e6e43cf6a3%5E/Formula/cppunit.rb;
      brew install protobuf log4cxx popt boost;
      travis_wait 30 brew install -s libswiften;
    fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install --user sleekxmpp;
    fi
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON . && make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make extended_test;
    else
      make test;
    fi
notifications:
  slack: spectrum2:CIlYHtxGMAaxs3qVHfwBzCuy
