language: cpp
python:
  - "2.7_with_system_site_packages"
virtualenv:
  system_site_packages: true
sudo: required
dist: trusty
before_script:
          - curl -k https://swift.im/keys/packages.key | sudo apt-key add -
          - echo "deb http://swift.im/packages/ubuntu/trusty beta main" | sudo tee -a /etc/apt/sources.list
          - echo "deb http://packages.spectrum.im/spectrum2/ trusty main" | sudo tee -a /etc/apt/sources.list
          - echo " deb http://packages.prosody.im/debian trusty main" | sudo tee -a /etc/apt/sources.list
          - sudo apt-get update -qq
          - sudo apt-get install -y --force-yes prosody ngircd python-sleekxmpp libswiften-dev libprotobuf-dev protobuf-compiler pidgin-dev liblog4cxx10-dev libpopt-dev libboost-dev libboost-signals-dev libboost-system-dev libboost-thread-dev libboost-locale-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-date-time-dev libcppunit-dev libcommuni-dev libminiupnpc-dev libnatpmp-dev
          - sudo killall lua5.1
install: "pip install --user sleekxmpp"
script:
          - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON . && make && make extended_test
notifications:
  slack: spectrum2:CIlYHtxGMAaxs3qVHfwBzCuy
