language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'deb https://packages.spectrum.im/spectrum2/ xenial main'
              key_url: 'https://packages.spectrum.im/packages.key'
            - sourceline: 'deb https://swift.im/packages/ubuntu/xenial release main'
              key_url: 'https://swift.im/keys/packages.key'
            - sourceline: 'deb https://packages.prosody.im/debian xenial main'
              key_url: 'https://prosody.im/files/prosody-debian-packages.key'
          packages:
            - git cmake prosody ngircd python-dateutil python-sleekxmpp libswiften-dev libprotobuf-dev protobuf-compiler libpurple-dev libglib2.0-dev libdbus-glib-1-dev liblog4cxx10-dev libpopt-dev libboost-dev libboost-signals-dev libboost-system-dev libboost-thread-dev libboost-locale-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-date-time-dev libcppunit-dev libcommuni-dev libminiupnpc-dev libnatpmp-dev libssl-dev libcurl4-openssl-dev libidn11-dev libxml2-dev libsqlite3-dev libqt4-dev libjsoncpp-dev libsasl2-modules-gssapi-mit libpurple-xmpp-carbons1
          update: true
    - os: linux
    - dist: trusty
      env: TRAVIS_DIST=trusty
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - cppunit
            - log4cxx
            - popt
            - jsoncpp
            - libswiften
            - protobuf
            update: true

before_script:
  sudo systemctl disable prosody;
  sudo service prosody stop;
  sudo rm /usr/include/mysql/plugin.h;
  cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON .;
  make;
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      make test;
    else
      make extended_test;
    fi
notifications:
  slack: spectrum2:CIlYHtxGMAaxs3qVHfwBzCuy
